### ISSUE TITLE
Add NETCoreApp support.

### ISSUE THREAD

**Issue by Muhomorik** [Wheelies/MarkdownLog#15]
Hi,
Could you add .Net Core support? Seems that there are no dependencies from framework.
.NET Standard Library maybe?

> Package MarkdownLog 0.9.3 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package MarkdownLog 0.9.3 supports:
>       - portable-net45+sl5 (.NETPortable,Version=v0.0,Profile=Profile24)
>       - portable-net45+win8 (.NETPortable,Version=v0.0,Profile=Profile7)
>       - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)

**Comment by Wheelies** [comment]
The latest package now uses .NET Standard 2.0
